version: '3.7'
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:14
    restart: always
    
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: root
      POSTGRES_DATABASE: admin
      POSTGRES_USER: root
      POSTGRES_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/run/postgresql
    ports:
      - "5435:5432"

